In [1]:
from joblib import dump, load
from model.training_data import *

## Decision Tree

In [2]:
dt = load("../data/decision_tree.pkl")

In [3]:
data = random_feature_sample_array(n=24)
print(data)

[[    29 126060      0      9      0      0     40]
 [    24  59146      0     13      0      0     40]
 [    28 222442      1      9      0      0     51]
 [    25 197871      1     13      0      0     50]
 [    35 538583      1      7   3674      0     40]
 [    30 263150      0      9      0      0     20]
 [    23 340432      1      9      0      0     40]
 [    67 222899      0     11      0      0     40]
 [    28 399123      1      9      0      0     40]
 [    21 298342      1     10      0      0     40]
 [    27 301514      1     10      0      0     40]
 [    46 201595      1      9      0      0     70]
 [    60 288684      1      3      0      0     40]
 [    44  27242      1     12      0      0     40]
 [    51 392668      1     16  15024      0     84]
 [    30 243841      0      9      0      0     40]
 [    56  70857      1      9      0      0     40]
 [    22 396895      1      3      0      0     35]
 [    36 194630      0     10      0      0     40]
 [    39 199

In [4]:
print(vkeys)
print("\n".join([str(x) for x in vetting]))

{'Feature': 0, 'count': 1, 'mean': 2, 'std': 3, 'min': 4, '25%': 5, '50%': 6, '75%': 7, 'max': 8}
['age', 48842.0, 38.64358543876172, 13.710509934443555, 17.0, 28.0, 37.0, 48.0, 90.0]
['fnlwgt', 48842.0, 189664.13459727284, 105604.02542315728, 12285.0, 117550.5, 178144.5, 237642.0, 1490400.0]
['sex-val', 48842.0, 0.6684820441423365, 0.47076356938045266, 0.0, 0.0, 1.0, 1.0, 1.0]
['education-num', 48842.0, 10.078088530363212, 2.5709727555922566, 1.0, 9.0, 10.0, 12.0, 16.0]
['capital-gain', 48842.0, 1079.0676262233324, 7452.019057655394, 0.0, 0.0, 0.0, 0.0, 99999.0]
['capital-loss', 48842.0, 87.50231358257237, 403.00455212435907, 0.0, 0.0, 0.0, 0.0, 4356.0]
['hours-per-week', 48842.0, 40.422382375824085, 12.391444024252307, 1.0, 40.0, 40.0, 45.0, 99.0]


In [5]:
res = vet_features(data)
print(res)

{'size': (24, 7), 'errors': [], 'warnings': ['feature fnlwgt value (59146.0) out of quartile range [117550.5, 237642.0] of training data in vector 1', 'feature fnlwgt value (538583.0) out of quartile range [117550.5, 237642.0] of training data in vector 4', 'feature fnlwgt value (263150.0) out of quartile range [117550.5, 237642.0] of training data in vector 5', 'feature fnlwgt value (340432.0) out of quartile range [117550.5, 237642.0] of training data in vector 6', 'feature fnlwgt value (399123.0) out of quartile range [117550.5, 237642.0] of training data in vector 8', 'feature fnlwgt value (298342.0) out of quartile range [117550.5, 237642.0] of training data in vector 9', 'feature fnlwgt value (301514.0) out of quartile range [117550.5, 237642.0] of training data in vector 10', 'feature fnlwgt value (288684.0) out of quartile range [117550.5, 237642.0] of training data in vector 12', 'feature fnlwgt value (27242.0) out of quartile range [117550.5, 237642.0] of training data in vec

In [6]:
prediction = dt.predict(data)
print(prediction)

[' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K'
 ' <=50K' ' <=50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' >50K' ' <=50K'
 ' <=50K' ' <=50K' ' <=50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K']


/Users/s.hendrickson/Library/Caches/pypoetry/virtualenvs/deploymachinelearningmodelstoproduction-si-4VBv0PsN-py3.8/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


## Deep NN

In [7]:
model_nn = load("../data/neural_net.pkl")
model_nn_sc = load("../data/neural_net_scaler.pkl")

df = pd.DataFrame(data, columns=features)
df1 = model_nn_sc.transform(df)
y_pred = model_nn.predict(df1)
print([np.argmin(x) for x in y_pred])

2022-06-02 13:16:28.080356: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


1/1 [==============================] - 0s 93ms/step
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]


## Deep NN Service

In [8]:
import requests

In [9]:
url = "http://127.0.0.1"
res = requests.get(url + "/version")
print(res.json())

{'version': '0.1.0', 'date': '2022-06-02T19:16'}


In [10]:
res = requests.get(url + "/examples/10")
print(res.json())

{'size': 10, 'data': [[35, 338320, 1, 9, 0, 0, 50], [65, 150095, 1, 13, 0, 0, 40], [46, 116906, 0, 14, 0, 2258, 35], [35, 62669, 1, 10, 0, 0, 55], [23, 117606, 0, 13, 0, 0, 40], [34, 30673, 1, 14, 0, 0, 55], [68, 69249, 1, 9, 0, 0, 10], [54, 141663, 1, 9, 0, 0, 15], [50, 116211, 1, 15, 0, 0, 52], [39, 366757, 1, 9, 0, 0, 35]]}


In [11]:
payload = res.json()

In [12]:
res = requests.post(url=url + "/vetter", json=payload)
print(res.json())

{'size': [10, 7], 'errors': [], 'warnings': ['feature fnlwgt value (338320.0) out of quartile range [117550.5, 237642.0] of training data in vector 0', 'feature fnlwgt value (116906.0) out of quartile range [117550.5, 237642.0] of training data in vector 2', 'feature fnlwgt value (62669.0) out of quartile range [117550.5, 237642.0] of training data in vector 3', 'feature fnlwgt value (30673.0) out of quartile range [117550.5, 237642.0] of training data in vector 5', 'feature fnlwgt value (69249.0) out of quartile range [117550.5, 237642.0] of training data in vector 6', 'feature fnlwgt value (116211.0) out of quartile range [117550.5, 237642.0] of training data in vector 8', 'feature fnlwgt value (366757.0) out of quartile range [117550.5, 237642.0] of training data in vector 9', 'feature education-num value (13.0) out of quartile range [9.0, 12.0] of training data in vector 1', 'feature education-num value (14.0) out of quartile range [9.0, 12.0] of training data in vector 2', 'featur

In [13]:
payload = {"size": 4, "data": [x.tolist() for x in data]}
prediction = requests.post(url=url + "/predict", json=payload)
print(prediction.json())

{'size': 24, 'data': [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
