In [1]:
from joblib import dump, load
from model.training_data import *

## Decision Tree

In [31]:
dt = load("../data/decision_tree.pkl")

In [32]:
data = random_feature_sample_array(n=24)
print(data)

[[    26 151626      0      9      0      0     40]
 [    46  67725      1     13      0      0     10]
 [    53 449376      1      9      0      0     40]
 [    34 110622      0     13      0      0     40]
 [    64 152172      1      6      0      0     40]
 [    45 118081      1     10   3103      0     42]
 [    17  19752      0      7      0      0     25]
 [    34 248795      0      9      0      0     45]
 [    31 409622      1     13      0      0     36]
 [    47  20956      1     13      0   1740     40]
 [    28 304960      0     12      0   1980     40]
 [    65 115513      1     13   5556      0     48]
 [    21  37783      0     10      0      0     38]
 [    36 298753      0     10      0      0     60]
 [    25 316688      1      9      0      0     40]
 [    21 208117      0      6      0      0     30]
 [    47 149366      1     13      0      0     40]
 [    20 117222      1     10      0      0     40]
 [    37 362006      0      9      0      0     40]
 [    70  77

In [33]:
print(vkeys)
print("\n".join([str(x) for x in vetting]))

{'Feature': 0, 'count': 1, 'mean': 2, 'std': 3, 'min': 4, '25%': 5, '50%': 6, '75%': 7, 'max': 8}
['age', 48842.0, 38.64358543876172, 13.710509934443555, 17.0, 28.0, 37.0, 48.0, 90.0]
['fnlwgt', 48842.0, 189664.13459727284, 105604.02542315728, 12285.0, 117550.5, 178144.5, 237642.0, 1490400.0]
['sex-val', 48842.0, 0.6684820441423365, 0.47076356938045266, 0.0, 0.0, 1.0, 1.0, 1.0]
['education-num', 48842.0, 10.078088530363212, 2.5709727555922566, 1.0, 9.0, 10.0, 12.0, 16.0]
['capital-gain', 48842.0, 1079.0676262233324, 7452.019057655394, 0.0, 0.0, 0.0, 0.0, 99999.0]
['capital-loss', 48842.0, 87.50231358257237, 403.00455212435907, 0.0, 0.0, 0.0, 0.0, 4356.0]
['hours-per-week', 48842.0, 40.422382375824085, 12.391444024252307, 1.0, 40.0, 40.0, 45.0, 99.0]


In [34]:
res = vet_features(data)
print(res)

{'size': (24, 7), 'errors': [], 'warnings': ['feature fnlwgt value (67725.0) out of quartile range [117550.5, 237642.0] of training data in vector 1', 'feature fnlwgt value (449376.0) out of quartile range [117550.5, 237642.0] of training data in vector 2', 'feature fnlwgt value (110622.0) out of quartile range [117550.5, 237642.0] of training data in vector 3', 'feature fnlwgt value (19752.0) out of quartile range [117550.5, 237642.0] of training data in vector 6', 'feature fnlwgt value (248795.0) out of quartile range [117550.5, 237642.0] of training data in vector 7', 'feature fnlwgt value (409622.0) out of quartile range [117550.5, 237642.0] of training data in vector 8', 'feature fnlwgt value (20956.0) out of quartile range [117550.5, 237642.0] of training data in vector 9', 'feature fnlwgt value (304960.0) out of quartile range [117550.5, 237642.0] of training data in vector 10', 'feature fnlwgt value (115513.0) out of quartile range [117550.5, 237642.0] of training data in vecto

In [35]:
prediction = dt.predict(data)
print(prediction)

[' <=50K' ' <=50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K'
 ' <=50K' ' <=50K' ' <=50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K'
 ' >50K' ' <=50K' ' >50K' ' >50K' ' <=50K' ' <=50K' ' >50K' ' <=50K']


/Users/s.hendrickson/Library/Caches/pypoetry/virtualenvs/deploymachinelearningmodelstoproduction-si-O4GGW7Z2-py3.8/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


## Deep NN

In [36]:
model_nn = load("../data/neural_net.pkl")
model_nn_sc = load("../data/neural_net_scaler.pkl")

df = pd.DataFrame(data, columns=features)
df1 = model_nn_sc.transform(df)
y_pred = model_nn.predict(df1)
print([np.argmin(x) for x in y_pred])

1/1 [==============================] - 0s 39ms/step
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0]


## Deep NN Service

In [8]:
import requests

In [9]:
url = "http://127.0.0.1"
res = requests.get(url + "/version")
print(res.json())

ConnectionError: HTTPConnectionPool(host='127.0.0.1', port=80): Max retries exceeded with url: /version (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x12728b220>: Failed to establish a new connection: [Errno 61] Connection refused'))

In [ ]:
res = requests.get(url + "/examples/10")
print(res.json())

In [ ]:
payload = res.json()

In [ ]:
res = requests.post(url=url + "/vetter", json=payload)
print(res.json())

In [ ]:
payload = {"size": 4, "data": [x.tolist() for x in data]}
prediction = requests.post(url=url + "/predict", json=payload)
print(prediction.json())

## Decision Tree NN Service

In [62]:
import requests

In [73]:
url = "http://127.0.0.1:5000"
url = "http://192.168.127.8/earnings-model"
res = requests.get(url + "/version")
print(res.json())

{'version': '0.1.0', 'date': '2022-06-13T23:09'}


In [74]:
res = requests.get(url + "/examples/20")
print(res.json())

{'size': 20, 'data': [[56, 155238, 1, 9, 0, 0, 40], [43, 37937, 1, 12, 0, 0, 43], [42, 248406, 1, 9, 0, 0, 40], [54, 154949, 0, 7, 0, 0, 40], [34, 84154, 1, 13, 0, 0, 50], [34, 196791, 0, 12, 0, 0, 25], [33, 99761, 0, 13, 0, 0, 15], [43, 390369, 1, 12, 0, 0, 40], [50, 94081, 1, 9, 0, 0, 40], [67, 212759, 1, 6, 0, 0, 2], [50, 120521, 1, 10, 0, 0, 50], [34, 199934, 1, 10, 7298, 0, 40], [37, 188563, 1, 9, 0, 0, 55], [57, 47857, 1, 10, 0, 0, 50], [46, 195023, 0, 9, 0, 0, 40], [63, 27653, 1, 9, 0, 0, 35], [25, 193773, 0, 9, 0, 0, 35], [38, 187264, 0, 9, 0, 0, 55], [26, 219796, 1, 13, 0, 0, 43], [70, 177806, 1, 11, 0, 0, 40]]}


In [75]:
payload = res.json()

In [76]:
res = requests.post(url=url + "/vetter", json=payload)
print(res.json())

{'size': [20, 7], 'errors': [], 'warnings': ['feature fnlwgt value (37937.0) out of quartile range [117550.5, 237642.0] of training data in vector 1', 'feature fnlwgt value (248406.0) out of quartile range [117550.5, 237642.0] of training data in vector 2', 'feature fnlwgt value (84154.0) out of quartile range [117550.5, 237642.0] of training data in vector 4', 'feature fnlwgt value (99761.0) out of quartile range [117550.5, 237642.0] of training data in vector 6', 'feature fnlwgt value (390369.0) out of quartile range [117550.5, 237642.0] of training data in vector 7', 'feature fnlwgt value (94081.0) out of quartile range [117550.5, 237642.0] of training data in vector 8', 'feature fnlwgt value (47857.0) out of quartile range [117550.5, 237642.0] of training data in vector 13', 'feature fnlwgt value (27653.0) out of quartile range [117550.5, 237642.0] of training data in vector 15', 'feature education-num value (7.0) out of quartile range [9.0, 12.0] of training data in vector 3', 'fe

In [77]:
prediction = requests.post(url=url + "/predict", json=payload)
print(prediction.json())

{'size': 20, 'data': [1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0]}


In [78]:
payload = {"size": 24, "data": [x.tolist() for x in data]}
prediction = requests.post(url=url + "/predict", json=payload)
print(prediction.json())

{'size': 24, 'data': [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0]}
