In [1]:
from joblib import dump, load
from model.training_data import *

## Decision Tree

In [2]:
dt = load("../data/decision_tree.pkl")

In [3]:
data = random_feature_sample_array(n=24)
print(data)

[[     64  209899       1      10       0       0      35]
 [     69  197288       1       9       0       0      35]
 [     48   58683       1      10       0       0      70]
 [     19  231688       1      10       0       0      20]
 [     57  237546       1      14       0       0      60]
 [     24   51973       0      13       0       0      20]
 [     24  197666       0      13       0       0      40]
 [     29  404998       1      11       0       0      90]
 [     53  161691       0      14    4865       0      40]
 [     30   54684       1      15       0       0      55]
 [     44  219591       1      10       0       0      40]
 [     63  201600       1      10       0    1902      60]
 [     43  281138       0       9       0       0      40]
 [     42 1097453       1      13       0       0      60]
 [     22  162667       1       9       0       0      50]
 [     76  178665       1       5       0       0      30]
 [     36   84294       1      13       0       0      7

In [4]:
prediction = dt.predict(data)
print(prediction)

[' <=50K' ' <=50K' ' >50K' ' <=50K' ' >50K' ' <=50K' ' <=50K' ' <=50K'
 ' <=50K' ' <=50K' ' <=50K' ' >50K' ' <=50K' ' >50K' ' <=50K' ' <=50K'
 ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K']


/Users/s.hendrickson/Library/Caches/pypoetry/virtualenvs/deploymachinelearningmodelstoproduction-si-4VBv0PsN-py3.8/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


## Deep NN

In [5]:
model_nn = load("../data/neural_net.pkl")
model_nn_sc = load("../data/neural_net_scaler.pkl")

df = pd.DataFrame(data, columns=features)
df1 = model_nn_sc.transform(df)
y_pred = model_nn.predict(df1)
print([np.argmin(x) for x in y_pred])

2022-06-01 16:59:42.904737: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


1/1 [==============================] - 0s 87ms/step
[0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


## Deep NN Service

In [6]:
import requests

In [7]:
url = "http://127.0.0.1"
res = requests.get(url + "/version")
print(res.json())

{'version': '0.1.0', 'date': '2022-06-01T22:59'}


In [8]:
res = requests.get(url + "/examples/10")
print(res.json())

{'size': 10, 'data': [[48, 65535, 1, 9, 0, 0, 50], [25, 212793, 1, 12, 0, 0, 50], [23, 170482, 1, 10, 0, 0, 45], [26, 267431, 0, 13, 0, 0, 20], [31, 274818, 0, 10, 0, 0, 40], [34, 157024, 0, 6, 0, 0, 20], [32, 187815, 1, 13, 0, 0, 45], [59, 114401, 0, 9, 0, 1504, 19], [24, 132053, 0, 12, 0, 0, 35], [33, 142675, 1, 13, 0, 0, 30]]}


In [9]:
payload = {"size": 4, "data": [x.tolist() for x in data]}
prediction = requests.post(url=url + "/predict", json=payload)
print(prediction.json())

{'size': 2, 'data': [1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}
