In [1]:
from joblib import dump, load
from model.training_data import *

## Decision Tree

In [2]:
dt = load("../data/decision_tree.pkl")

In [3]:
data = random_feature_sample_array(n=24)
print(data)

[[    49 148437      1     13      0      0     60]
 [    24  72119      1     13   2202      0     30]
 [    24 203518      0     13      0      0     40]
 [    37 123586      1     13      0   1902     73]
 [    53 424079      1     14  15024      0     55]
 [    25 201579      1      5      0      0     40]
 [    36 155537      1      9      0      0     40]
 [    62 153891      1     13      0      0     50]
 [    26 250261      1      2      0      0     55]
 [    24 191269      0     13      0      0     65]
 [    44 225263      0     10      0   1408     46]
 [    30 119197      1     14      0      0     50]
 [    23  86939      1      9      0      0     40]
 [    67 110122      1      9      0      0     32]
 [    22 102632      1      9      0      0     41]
 [    30 214993      1      9      0      0     40]
 [    22 211798      1     11      0      0     10]
 [    44 151780      0     10      0      0     40]
 [    43  60001      1     10      0      0     40]
 [    31  85

In [4]:
prediction = dt.predict(data)
print(prediction)

[' <=50K' ' <=50K' ' <=50K' ' >50K' ' >50K' ' <=50K' ' <=50K' ' >50K'
 ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K' ' >50K' ' <=50K' ' <=50K'
 ' <=50K' ' <=50K' ' <=50K' ' >50K' ' <=50K' ' <=50K' ' <=50K' ' <=50K']


/home/scott/.cache/pypoetry/virtualenvs/deploymachinelearningmodelstoproduction-si-wSOjrWpr-py3.8/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


## Deep NN

In [5]:
model_nn = load("../data/neural_net.pkl")
model_nn_sc = load("../data/neural_net_scaler.pkl")

df = pd.DataFrame(data, columns=features)
df1 = model_nn_sc.transform(df)
y_pred = model_nn.predict(df1)
print([np.argmin(x) for x in y_pred])

2022-06-01 18:02:55.535621: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:975] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-01 18:02:55.557305: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib/cuda/include:/usr/lib/cuda/lib64:
2022-06-01 18:02:55.557332: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1850] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2022-06-01 18:02:55.558035: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary

1/1 [==============================] - 0s 58ms/step
[1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


## Deep NN Service

In [6]:
import requests

In [7]:
url = "http://127.0.0.1"
res = requests.get(url + "/version")
print(res.json())

{'version': '0.1.0', 'date': '2022-06-02T00:02'}


In [8]:
res = requests.get(url + "/examples/10")
print(res.json())

{'size': 10, 'data': [[27, 176727, 1, 13, 0, 0, 40], [56, 131608, 1, 10, 0, 0, 40], [55, 89182, 0, 8, 0, 0, 40], [47, 282830, 1, 12, 0, 0, 40], [32, 80557, 1, 9, 0, 0, 70], [69, 197080, 1, 8, 9386, 0, 60], [74, 272667, 0, 12, 0, 0, 20], [23, 183789, 1, 9, 0, 0, 40], [27, 506436, 0, 10, 0, 0, 40], [31, 264936, 0, 10, 0, 0, 40]]}


In [9]:
payload = {"size": 4, "data": [x.tolist() for x in data]}
prediction = requests.post(url=url + "/predict", json=payload)
print(prediction.json())

{'size': 2, 'data': [1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}
